// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingContext;

namespace ParkingContext.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200628134721_Fifth")]
    partial class Fifth
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ParkingModel.Carro", b =>
                {
                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsuarioCpf")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Placa");

                    b.HasIndex("UsuarioCpf");

                    b.ToTable("Carros");
                });

            modelBuilder.Entity("ParkingModel.Conferencia", b =>
                {
                    b.Property<int>("Inf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Informacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placa")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Inf");

                    b.HasIndex("Placa")
                        .IsUnique()
                        .HasFilter("[Placa] IS NOT NULL");

                    b.ToTable("Conferencias");
                });

            modelBuilder.Entity("ParkingModel.PatioEstacionamento", b =>
                {
                    b.Property<string>("Placa")
                        .HasColumnName("PlacaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Duracao")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<DateTime>("HoraEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraSaida")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Mensalista")
                        .HasColumnType("bit");

                    b.Property<int>("Vaga")
                        .HasColumnType("int");

                    b.Property<double>("ValorFinal")
                        .HasColumnType("float");

                    b.HasKey("Placa");

                    b.ToTable("PastioEstacionamento");
                });

            modelBuilder.Entity("ParkingModel.Usuario", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Cpf");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ParkingModel.Carro", b =>
                {
                    b.HasOne("ParkingModel.Usuario", "Usuario")
                        .WithMany("Carros")
                        .HasForeignKey("UsuarioCpf");
                });

            modelBuilder.Entity("ParkingModel.Conferencia", b =>
                {
                    b.HasOne("ParkingModel.Carro", "Carro")
                        .WithOne("Conferencia")
                        .HasForeignKey("ParkingModel.Conferencia", "Placa");
                });
#pragma warning restore 612, 618
        }
    }
}
